'''
Declare the namespace ``pydap`` here.
'''
__import__('pkg_resources').declare_namespace(__name__)

try:
    # NOTE: the `version.py` file must not be present in the git repository
    #   as it is generated by setuptools at install time
    from .version import __version__
except ImportError:  # pragma: no cover
    # Local copy or not installed with setuptools
    __version__ = "999"
